name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

    
env:
  BUILD_DIR: build
  PDF_NAME: monografia.pdf

jobs:
  build:
    name: build ğŸ› ï¸ 
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: ğŸ›ï¸ Checkout code
        uses: actions/checkout@v4
      - name: ğŸ“œ Make PDF
        run: make
      - name: ğŸ“¤ Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: monografia
          path: ${{ env.BUILD_DIR }}/${{ env.PDF_NAME }}

  deploy:
    name: deploy ğŸš€
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout code
        uses: actions/checkout@v4
      - name: ğŸ“¥ Upload PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: monografia
      - name: ğŸ“‚ Move PDF to output directory
        run: |
          mkdir out
          mv ${{ env.PDF_NAME }} out
      - name: ğŸš€ Upload PDF to orphan branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: pdf



